name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set timestamp variable
      run: echo "::set-env name=TIMESTAMP::$(date +%s)"
    - name: Authenticate with Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username mtvirux --password-stdin
    
    - name: Build the Docker image (ssl)
      run: |
        docker build . --file Dockerfile_ssl    -t mtvirux/php-8.0-apache-mysqli-sockets:latest
        docker build . --file Dockerfile_ssl    -t mtvirux/php-8.0-apache-mysqli-sockets:ssl-${{ env.TIMESTAMP }}

    - name: Build the Docker image (ssl)
    - run: |
        docker build . --file Dockerfile_no-ssl -t mtvirux/php-8.0-apache-mysqli-sockets:no-ssl-latest
        docker build . --file Dockerfile_no-ssl -t mtvirux/php-8.0-apache-mysqli-sockets:no-ssl-${{ env.TIMESTAMP }}
        
    - name: Push ssl tag Docker Image
    - run: |
        docker push mtvirux/php-8.0-apache-mysqli-sockets:no-ssl-latest
        docker push mtvirux/php-8.0-apache-mysqli-sockets:no-ssl-${{ env.TIMESTAMP }}
        
    - name: Push no-ssl tag Docker Image
    - run: |
        docker push mtvirux/php-8.0-apache-mysqli-sockets:latest
        docker push mtvirux/php-8.0-apache-mysqli-sockets:ssl-${{ env.TIMESTAMP }}
